default:
  image: "docker.io/abb128/android-build:v3@sha256:fc062b587302a66902b2abb463d886b53ec173e157d8297d16b9f00bce4633e7"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  GIT_STRATEGY: clone
  GIT_DEPTH: 0

stages:          # List of stages for jobs, and their order of execution
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - export VERSION_NAME=`git describe --tags --dirty`
    - export VERSION_CODE=`git rev-list --first-parent --count HEAD`
    - echo $VERSION_CODE $VERSION_NAME
    - ./setUpPropertiesCI.sh
    - gradle assembleRelease -s
    - mv build/outputs/apk/release/latinime-release.apk ./keyboard-$VERSION_NAME.apk
    - echo "Keyboard $VERSION_NAME - https://gitlab.futo.org/alex/latinime/-/jobs/$CI_JOB_ID/artifacts/raw/keyboard-$VERSION_NAME.apk"
    - echo $VERSION_CODE $VERSION_NAME
  artifacts:
    name: "keyboard-$VERSION_NAME"
    paths:
      - ./*.apk
  when: manual