name: Bug Report
description: Let us know about an unexpected error, a crash, or an incorrect behavior.
labels: ["bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to fill out this bug report.
        
        The [android-keyboard](https://github.com/futo-org/android-keyboard) issue tracker is reserved for issues relating to the FUTO Keyboard Android Application

        For general usage questions, please see the [FUTO Keyboard Zulip Channel](https://chat.futo.org/#narrow/stream/53-Keyboard) or the [FUTO Keyboard Discord](https://keyboard.futo.org/discord)

        Please open bug reports one at a time. If you have 3 separate feature requests/bugs, do not combine them into one issue, this makes it really difficult to track and understand them.

        ## Filing a bug report

        To fix your issues faster, we need clear reproduction cases - ideally allowing us to make it happen locally. 
        * Please include all needed context. For example, Device, OS, Application, any relevant settings.
        * If you've found a particular series of interactions can introduce buggy behavior, please label those steps 1-n with markdown

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: keyboard-version
    attributes:
      label: Keyboard Version
      description: Open the FUTO Keyboard settings and look for the version name at the bottom, or in the Help & Feedback menu. Please make sure you're up-to-date before filing a bug report. Reports from outdated versions may be closed.
      placeholder: "0.1.22"
    validations:
      required: true

  - type: textarea
    id: editor-info
    attributes:
      label: Text field info
      description: If this issue happens in some text fields and not others, it may be related to that specific app's text field. To help diagnose these issues, please enable the Debug Info action and attach a screenshot of the Editor Info section, or describe the app and the text field.
      placeholder: (e.g. Search bar in DuckDuckGo)
    validations:
      required: false